format = """$time$git_branch$git_status$package$rust$docker_context$status$cmd_duration\n$directory(blue)$character"""

[character]
success_symbol = "[❯](green bold)"
error_symbol = "[❯](red bold)"
vicmd_symbol = "[V](green bold)" # not wirking idk why

[time]
disabled = false
format = '❯ [$time]($style)'
time_format = "%T"
utc_time_offset = "+1"
# time_range = "10:00:00-14:00:00"

[git_branch]
format = " ❯ [$symbol$branch](bold red)"

[package]
format = " ❯ [$symbol$version]($style)"

[docker_context]
format = " ❯ [$symbol$context]($style)"

[git_status]
format = " ([\\[$all_status$ahead_behind\\]]($style))"

[rust]
format = " ❯ [$symbol$version]($style)"

[status]
format = ' ❯ exit code [$status]($style) \([$common_meaning]($style)\)'
disabled = false

[cmd_duration]
format = " ❯ took [$duration]($style)"
